import React from 'react';
import { ChartCard } from './charts/ChartCard';

const HMMViz = () => {
  return (
    <div className="my-8">
      <ChartCard title="Hidden Markov Model (HMM) Architecture" subtitle="An HMM consists of hidden states (z) that evolve over time and observations (x) that are generated by those states.">
        <div className="ml-scroll-x">
          <div className="ml-min-w-hmm flex flex-col items-center p-6 space-y-8">
            {/* Timeline of Hidden States */}
            <div className="flex items-center space-x-12 relative">
              <div className="absolute top-1/2 left-0 right-0 h-1 bg-gray-200 -z-10 translate-y-[-50%]"></div>
              {[1, 2, 3].map((t) => (
                <div key={`z-${t}`} className="flex flex-col items-center">
                  <div className="w-16 h-16 rounded-lg border-4 border-[#8884d8] bg-white flex items-center justify-center font-bold text-xl text-[#8884d8] shadow-sm">
                    z<sub>{t}</sub>
                  </div>
                  <div className="mt-2 text-[10px] font-bold text-gray-400 uppercase tracking-wider">Hidden State</div>
                </div>
              ))}
              <div className="text-2xl font-bold text-gray-300">...</div>
            </div>

            {/* Vertical Emission Arrows */}
            <div className="flex space-x-24 text-gray-300">
              {[1, 2, 3].map((t) => (
                <div key={`arrow-${t}`} className="flex flex-col items-center">
                  <svg width="20" height="40" viewBox="0 0 20 40">
                    <path d="M10 0 V35" stroke="currentColor" strokeWidth="2" markerEnd="url(#arrow-head)" />
                    <defs>
                      <marker id="arrow-head" markerWidth="10" markerHeight="10" refX="5" refY="5" orient="auto">
                        <path d="M0,0 L10,5 L0,10 z" fill="currentColor" />
                      </marker>
                    </defs>
                  </svg>
                </div>
              ))}
            </div>

            {/* Timeline of Observations */}
            <div className="flex items-center space-x-12">
              {[1, 2, 3].map((t) => (
                <div key={`x-${t}`} className="flex flex-col items-center">
                  <div className="w-16 h-16 rounded-full border-4 border-[#82ca9d] bg-white flex items-center justify-center font-bold text-xl text-[#82ca9d] shadow-sm">
                    x<sub>{t}</sub>
                  </div>
                  <div className="mt-2 text-[10px] font-bold text-gray-400 uppercase tracking-wider">Observation</div>
                </div>
              ))}
              <div className="text-2xl font-bold text-gray-300">...</div>
            </div>
          </div>
        </div>

        <div className="mt-4 grid grid-cols-2 gap-4 text-xs">
          <div className="p-3 bg-indigo-50 border border-indigo-100 rounded text-indigo-800">
            <strong>Transitions:</strong> p(z<sub>t</sub> | z<sub>t-1</sub>) - How the hidden world changes.
          </div>
          <div className="p-3 bg-emerald-50 border border-emerald-100 rounded text-emerald-800">
            <strong>Emissions:</strong> p(x<sub>t</sub> | z<sub>t</sub>) - How the hidden world produces evidence.
          </div>
        </div>
      </ChartCard>
    </div>
  );
};

export default HMMViz;
